### ISSUE TITLE
AttributeError: module 'array' has no attribute 'show_array_menu'

### ISSUE THREAD

**Issue by averylicious** [sarapmagcode/Patrick-Star-DSA-System#2]
### Problem:
**'array'** variable name is a reserved keyword for a known Python module resulting in an unexpected behavior

### Expected Behavior
_Fetch the display menu from **array.py**_
===== Array =====
Choose:
1. Create array
2. Show original
3. Show sorted
4. Search element
5. Go back

### Actual Behavior
Traceback (most recent call last):
  File "d:\Users\Avery\Documents\GitHub\Patrick-Star-DSA-System\Python\main.py", line 88, in <module>
    main()
  File "d:\Users\Avery\Documents\GitHub\Patrick-Star-DSA-System\Python\main.py", line 76, in main
    show_data_structures_menu()
  File "d:\Users\Avery\Documents\GitHub\Patrick-Star-DSA-System\Python\main.py", line 39, in show_data_structures_menu
    array.show_array_menu()
AttributeError: module 'array' has no attribute 'show_array_menu'

### Workaround
Assign a different var name for _**'array.py'**_ to something like **'aray.py'**, program should now work flawlessly

**Comment by sarapmagcode** [comment]
noted lods

**Comment by imcrom** [comment]
Paayos naman po! Taena mo converge 2 star review

**Comment by sarapmagcode** [comment]
crom magcode ka diyan
